version: '3.7'

services:

  docker-redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=redis_very_secret_password
    logging:
      driver: none
    networks:
      - java_develop

  docker-postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgress_very_secret_password
      - POSTGRES_USER=docker
      - POSTGRES_DB=mcu
    volumes:
      - ./data/src/main/resources/10_init_postgres_db.sql:/docker-entrypoint-initdb.d/10_init_postgres_db.sql
      - ./data/src/main/resources/20_insert_into_movies.sql:/docker-entrypoint-initdb.d/20_insert_into_movies.sql
    logging:
      driver: none
    networks:
      - java_develop

  docker-mysql:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=mysql_very_secret_root_password
      - MYSQL_DATABASE=mcu
      - MYSQL_USER=docker
      - MYSQL_PASSWORD=mysql_very_secret_docker_password
    volumes:
      - ./data/src/main/resources/10_init_mysql_db.sql:/docker-entrypoint-initdb.d/10_init_mysql_db.sql
      - ./data/src/main/resources/20_insert_into_movies.sql:/docker-entrypoint-initdb.d/20_insert_into_movies.sql
    logging:
      driver: none
    networks:
      - java_develop

  spring-boot:
    image: adoptopenjdk/openjdk11
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      - spring.profiles.active=postgres
      - spring.h2.console.enabled=false
    volumes:
      - ./web/target/web-0.2.jar:/usr/src/web-0.2.jar
    depends_on:
      - docker-postgres
      - docker-mysql
      - docker-redis
    command: java -jar /usr/src/web-0.2.jar
    networks:
      - java_develop

networks:
  java_develop:
