version: '3.7'

services: 
  postgres:
    image: postgres
    ports: 
      - "5432:5432"
    environment: 
      - POSTGRES_PASSWORD=postgress_very_secret_password
      - POSTGRES_USER=docker
      - POSTGRES_DB=mcu
    volumes:
      - ./data/src/main/resources/10_init_db_and_tables.sql:/docker-entrypoint-initdb.d/10_init_db_and_tables.sql
    networks:
      - java_develop

networks:
  java_develop:
